name: Aggiorna file Excel da OneDrive locale

on:
  schedule:
    - cron: "0 11 * * *" # ogni giorno alle 12:00 italiane (11:00 UTC)
  workflow_dispatch:      # per avvio manuale

jobs:
  update_excel:
    runs-on: self-hosted  # usa il runner locale sul Mac

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copia file Excel dal OneDrive locale
        run: |
          echo "📂 Copia del file Excel dal percorso OneDrive locale..."
          cp "/Users/fabioscaranello/Library/CloudStorage/OneDrive-SHTSrl/TUTTO CLIENTI TOP/GESTIONE_CLIENTI.xlsm" ./GESTIONE_CLIENTI.xlsm || (echo "❌ ERRORE: file non trovato in OneDrive" && exit 1)

      - name: Commit e push del nuovo file Excel
        run: |
          git config user.name "Fabio74-bit"
          git config user.email "fabio.scaranello@shtsrl.com"
          git add GESTIONE_CLIENTI.xlsm
          git commit -m "🔄 Aggiornamento automatico file Excel da OneDrive" || echo "Nessuna modifica da committare"
          git push origin main
